---
# Copyright (c) 2024 Cisco and/or its affiliates.

# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at

#               https://developer.cisco.com/docs/licenses

# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.

- name: Install Firmware Updates for ESXi Hosts
  hosts: "TheServers"
  gather_facts: false
  connection: local
  serial: 1

  tasks:
    - name: "Remove ESXi host from service"
      ansible.builtin.include_tasks: ./tasks/001-enter-maintenance-mode.yaml
      tags:
        - enterMaintenanceMode
        - maintenanceMode

    # A CIMC Token is Required to trigger the Firmware Update
    - name: "Get Token from CIMC"
      ansible.builtin.include_tasks: ./tasks/002-get-cimc-token-XML.yaml
      when: mode == "xml_api"
      tags:
        - token

    - name: "Trigger Update using XML API"
      ansible.builtin.include_tasks: ./tasks/003a-start-firmware-upgrade-XML-API.yaml
      when: mode == "xml_api" and cimc_token != 'None'
      tags:
        - xmlFirmwareUpgrade

    - name: "Track Reboot"
      ansible.builtin.include_tasks: ./tasks/004-check-esxi-host-status.yaml
      tags:
        - statusCheck

    - name: "Return ESXi to Service"
      ansible.builtin.include_tasks: ./tasks/005-exit-maintenance-mode.yaml
      tags:
        - exitMaintenanceMode
        - maintenanceMode
