- name: Enter Host Into Maintenace Mode
  community.vmware.vmware_maintenancemode:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ lookup('ansible.builtin.env', 'VCENTER_PASSWORD') }}"
    validate_certs: "{{ validate_certs }}"
    esxi_hostname: "{{ ansible_host }}"
    evacuate: "{{ mm_evacuate }}"
    timeout: "{{ mm_timeout }}"
    state: present
  tags:
    - always
